### ISSUE TITLE
NUnit does not shink test data

### ISSUE THREAD

**Issue by egor-laufer** [fsharp/FsCheck#101]
Hi,

I'm using FsCheck 2.0.0 with FsCheck.NUnit 2.0.0, C# API. 

No matter what I do, the data is not shrunk.

Simple example:

```C#
[FsCheck.NUnit.Property]
public void Prop()
{
    Spec.ForAny((List<int> list) => Assert.Less(list.Sum(), 20))
        .QuickCheckThrowOnFailure();
}
```

Running this in VS gives the following:

```C#
System.Exception : Falsifiable, after 25 tests (0 shrinks) (StdGen (1661770773,296011564)):
seq [-4; -1; -20; -10; ...]
```

The example might not be so great, but I have double-checked that this happens every time even if there is a possibility to falsify property with a sublist.
This also happens with types for which I have provided my own Shrink implementation.

I'm quite new to the library and would be glad to hear if I'm just missing something :)

**Comment by kurtschelfthout** [comment]
If you use QuickCheckThrowOnFailure you don't need FsCheck.NUnit at all, just make it a normal NUnit test. That would be the first thing to try.

**Comment by egor-laufer** [comment]
Just updated to FsCheck 2.0.1

I've noticed that ```FsCheck.Fluent``` is gone now, but I'm fine with it, as ```Prop``` seems to be providing everything I needed from ```Spec``` anyway.

So I rewrote my properties with ```Prop``` and also changed ```[FsCheck.NUnit.Property]``` to plain NUnit ```[Test]```, and both built-in and custom shrinkers now work as expected.

Thanks for your help!

**Comment by kurtschelfthout** [comment]
Yes - nuget related shenanigans. Fluent should have never been in 2.0. Long story, will write up later. You tipped me off though, so many thanks for raising  the issue and glad to hear it's working now.
