### ISSUE TITLE
Nuget Package Requires FSharp.Core 4.3.1.0

### ISSUE THREAD

**Issue by mbuhot** [fsharp/FsCheck#59]
This version of FSharp.Core is not officially supported in VS 2012.

**Comment by kkm000** [comment]
@mbuhot Care to share package ID and version of the package "FSharp.Core for F# 3.1+, Microsoft signed" that you mentioned? It does not "exist" at nuget.org any more, but since packages are always available by ID, I'll be able to fetch it.

There is [a package](https://www.nuget.org/packages/FSharp.Core/) of the same version of FSharp.Core but the binaries were built (and therefore signed) by another entity than Microsoft, so eventually I'll end up with 2 different FSharp.Core 4.3.1.0 libraries loaded, since they have different strong names. DLL hell was a warm Florida beach compared to what .NET has introduced :(((

**Comment by mausch** [comment]
https://www.nuget.org/packages/FSharp.Core/ is the de facto standard package at the moment. You can follow https://github.com/fsharp/fsharp/issues/352 for updates on the status of the "official" NuGet package.

**Comment by kkm000** [comment]
Thanks. I already figured the assembly is really signed by Microsoft, so there won't be a problem using the binary in a project that nothing else can possibly depend on.

**Comment by mbuhot** [comment]
Seems like adding a nuget dependency on the more recent FSharp.Core would prevent new users from stumbling at this step.

**Comment by mausch** [comment]
+1 to the suggestion above. It also helps C# users, who shouldn't have to care about what FSharp.Core is or what version is needed. @kurtschelfthout what do you think?

**Comment by kurtschelfthout** [comment]
Don't fully understand the ramifications I must say, but it sounds good. Essentially it just means that all FsCheck packages would have a dependency on that package?

**Comment by mausch** [comment]
The dependency only needs to be declared for https://www.nuget.org/packages/FsCheck/ . Other packages depending on that one will fetch the dependency automatically.

**Comment by kurtschelfthout** [comment]
Would it cause conflicts if used with other F# libraries in the same project that do not have this fsharp.core package dependency?

**Comment by mausch** [comment]
No, NuGet inserts assembly binding redirects where needed. Conflicts are caused by *not* declaring this dependency on FSharp.Core, as this means that the binding redirect has to be added manually (or the FSharp.Core package has to be installed manually), such as described in this issue and https://github.com/fsharp/FsCheck/issues/48 and https://github.com/fsharp/FsCheck/issues/39

**Comment by kurtschelfthout** [comment]
So I tried to test what happens here: https://github.com/fsharp/FsCheck/commit/163062f7053741b690754f0aed37f7fe42819af3 

Basically what I ran is paket add nuget FSharp.Core --interactive and let it add references to all the fsproj files (the csproj files don't need the dependency apparently)

It's just weird. The references to the existing FSharp.Core are not replaced; the only thing it does is adding a big Choose to all the fsproj files, but it doesn't contain anything. The existing refs to Reference Assemblies are still there.

The example csproj I have don't seem to need a dependency on FSharp.Core directly; so I think if you would install the FsCheck package + FSharp.Core dependency there it would be fine. However if you have a dependency on FSharp.Core already it doesn't seem to replace them or add binding redirects, so those folks might be in a more confused state than before.

In any case I am none the wiser. Still not sure if this is going to help or hurt.

**Comment by kkm000** [comment]
Will adding a redirect in `init.ps1` explicitly do the trick (v. `Add-BindingRedirect`).

But this feels like opening a can of worms...

**Comment by kurtschelfthout** [comment]
I think that's the next problem ;) For now I would have been happy if it would have replaced the actual reference...then again, maybe it was being smart about it because it noticed I already had the right references...hm. I hate having to discover the behavior of these things by experimentation.

**Comment by mausch** [comment]
@kurtschelfthout About https://github.com/fsharp/FsCheck/commit/163062f7053741b690754f0aed37f7fe42819af3 : that big Choose comes from paket, not from NuGet, I'd ask the paket authors about it.
Anyway what I meant before was declaring https://www.nuget.org/packages/FSharp.Core/ as a dependency in FsCheck.nuspec. Whatever the FsCheck fsproj itself does is a separate thing IMHO.
About C# projects: are you sure you tried that on a new VS2012 C# project?

**Comment by kurtschelfthout** [comment]
Ok, that's useful about paket, thanks.

I understand just declaring the dependency is what's wanted here, but I just wanted to eat my own dog food. Seems that if we expect folks to build and work with the FSharp.Core nuget package, it would be desirable that FsCheck is built against it as well.

I didn't try on a new C# project, but meanwhile it did ask me to add the reference, so maybe I just got myself confused...

**Comment by kurtschelfthout** [comment]
Oh ok, so this is a paket bug and it is fixed. So I'll just retry and then hopefully all will be well. https://github.com/fsprojects/Paket/issues/579

**Comment by kurtschelfthout** [comment]
Latest builds on that branch seem better. I'm more comfortable adding this dependency now to the FsCheck package. Probably tomorrow.

**Comment by monkieboy** [comment]
I had problems with a solution in 2013 when I was using my laptop which only had 2012 I had to do the following hack to get it working:

      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.0.0" />
      </dependentAssembly>
    </assemblyBinding>

**Comment by kurtschelfthout** [comment]
That should be solved in 2.0, it has an explicit dependency on the right FSharp.Core nuget package.
