### ISSUE TITLE
Use Paket for internal dependencies management

### ISSUE THREAD

**Issue by Andrea** [fsharp/FsCheck#65]
Paket is a tool that works on top of nuget that AFAIU
- manages internal packages. If two packages reference conflicting versions of a package, NuGet will silently take the latest version (read more). You have no control over this process.
- faster because it caches packages
- can download from github
- can use files from github ( a la Simple.Json)
- easy to see dependecies

At the moment may not be a pain point but I like that it's faster  and the fact that you wouldn't have multiple versions of the same project hanging around in your dependencies .

I am sure there is more that I just don't know, maybe @forki can add to this :D

**Comment by kurtschelfthout** [comment]
Solved by #77.
