### ISSUE TITLE
No documentation for constraining inputs without using attributes

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fsharp/FsCheck#78]
It seems there should be a way to constrain inputs to fscheck without relying on custom attributes.  I'm particularly interested because it seems the attributes aren't being picked up or listened to while running FsCheck in LinqPad. http://share.linqpad.net/oxhh8x.linq tweet conversation thread @ http://t.co/WRpySN3yLp

**Comment by kurtschelfthout** [comment]
Not sure what the question is. Documentation on how to write generators is here: https://fsharp.github.io/FsCheck/TestData.html

**Comment by ImaginaryDevelopment** [comment]
I had not seen that page, if there's enough documentation (still reading through it) on that page to reproduce [this](http://blog.ploeh.dk/2015/01/10/diamond-kata-with-fscheck/) without attributes, then this is a non-issue.

**Comment by kurtschelfthout** [comment]
Should be straightforward to reproduce. Also read Running Tests, may be closer to what you're after.

FYI, it comes over as quite impolite to start the thread with "No documentation for..." without having read the documentation.

**Comment by ImaginaryDevelopment** [comment]
I had searched the documentation, I mentioned in my last reply that I had not seen/found that particular page.
