### ISSUE TITLE
What is the latest version of FsCheck built against FSharp.Core 4.3.0.0?

### ISSUE THREAD

**Issue by kkm000** [fsharp/FsCheck#80]
This is related to #59. I have the same issue only with NUnit runner. Provided I cannot install a newer FSharp.Core version into this project, what is the latest version of FsCheck NuGet package that I can use in VS2012?

**Comment by mausch** [comment]
Why can't you install a newer FSharp.Core for your test project? https://www.nuget.org/packages/FSharp.Core/ should work just fine in VS2012.

**Comment by kkm000** [comment]
Out of curiosity, what are the exact features that you are using out of FSharp.Core 4.3.1.0 that were not available in earlier versions? For one, FSUnit.dll from the latest package references FSharp.Core 2.3.0.0, and is very compatible accross multiple environments. The upgrade to 4.3.1.0, on the other end, essentially narrowed down compatibility of FsCheck to VS 2013 only.

**Comment by kkm000** [comment]
> Why can't you install a newer FSharp.Core for your test project?
I'll check, but it seems to me that wit was not signed by Microsoft. So I'll eventually end up with 2 versions of FSharp.Core 4.3.1.0, differing only by their strong name.

I guess might be okay for a unit test only project. But we have set for ourselves pretty strong rules (written in sweat and tears, really) against "assembly hell."

**Comment by mausch** [comment]
FSharp.Core 4.3.1.0 works fine on any .NET-4.0-enabled Visual Studio, it's just another .NET 4.0 library.
FsCheck itself requires (as of 1.0.0) .NET 4.5 because of https://github.com/fsharp/FsCheck/commit/f248b094662b28b1c846f0e81e870129c10cbbda .

**Comment by kkm000** [comment]
I see. So you had to upgrade because FSharp.Core 4.3.0.0 is incompatible with .NET 4.5. I did not know that.

As for the signature, the binary in package is Microsoft signed, `FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` -- same token as in the version that comes with F# 3.1.

**Comment by mausch** [comment]
FSharp.Core 4.3.0.0 is not incompatible with .NET 4.5.

**Comment by kkm000** [comment]
Ah, sorry, I think I was confused. I thought you were answering my curious question why FsCheck required the newest and greatest FSharp.Core assembly.

**Comment by mausch** [comment]
For a previous explanation of this same question see https://github.com/fsharp/FsCheck/issues/39#issuecomment-50079416

**Comment by kkm000** [comment]
I see. Right, it would annoy people either way. Too bad I have no idea how to add a redirect for VS test runners, if that's even possible in a portable way (if that was only my own computer, I'd add a machine-wide redirect and forgot about all the versioning issues).

I think I'll add the FSCore package to the project, and we rather should review our system assembly dependency rules. Thanks for all the pointers!

**Comment by kurtschelfthout** [comment]
Depends on the test runner. I think xunit picks up redirects if you add them to app.config of the test dll. If I remember correctly, nunit claims it does that but I never got it to work; what should always work is to add the redirect to the runner exe (e.g. nunit.runner.exe.config)

**Comment by kkm000** [comment]
@kurtschelfthout : No, nunit does not pick up redirects from test dll config for me as well. Interesting that they claim it's working--I'll try to follow that hint, thanks. As for changing the runner config, it comes with a nuget package. I can change a local copy, but the tests won't work on other developer's machines. 

Anyway, I think I'll just use the upgraded F# core library in test projects only.

**Comment by kurtschelfthout** [comment]
I am not 100% sure, could be misremembering. Don't understand frankly why so many people prefer NUnit. Both as a user of the test framework, writer of an extension, and bug reporter it has consistently disappointed me. But anyway, ranting doesn't help you :)

**Comment by kkm000** [comment]
@kurtschelfthout: NUnit supports parametrized tests, and MS own runner does not (strictly speaking it does, by using a database, which is not quite convenient really). With xUnit, I had threading problems and could not capture test output. The former is solved using very cryptic attributes, and the latter can be worked around but requires additional code. What are you using?

**Comment by kurtschelfthout** [comment]
xUnit.
