### ISSUE TITLE
Examples of using NonNull<_>

### ISSUE THREAD

**Issue by kkm000** [fsharp/FsCheck#81]
I cannot figure out how to use the `NonNull<'t>` and `Arb.Default.NonNull<'t>` added in #31. I rewrote

    (Arb.from<string> |> Arb.filter (fun s -> s <> null)).Generator

as

    (Arb.Default.NonNull<string>() |> Arb.convert (fun (NonNull s) -> s) NonNull).Generator

but it did not make it more readable or clear. Am I doing it wrong? Examples would be helpful, but I could not find any.

**Comment by mausch** [comment]
The difference is that the type `string` has `null` as a value while `NonNull<string>` does not. I.e. this compiles: `let a : string = null` but this does not: `let a : NonNull<string> = null` . 
FsCheck includes generators for `string` and `NonNull<'a>` so you don't have to write the generators you just wrote. If your property has a parameter of type `string` FsCheck will generate a (possibly null) string, and if the parameter is of type `NonNull<string>` it will generate non-null strings.

**Comment by kkm000** [comment]
I see. So actually I should write e. g.

    Prop.forAll (Arb.from<NonNull<string>>) (fun (NonNull astring) -> ....)

-- correct? I think that mentioning that in the documentation would make a lot of sense, if you would consider such a request.

**Comment by mausch** [comment]
You don't need to call the generator explicitly if you're not going to manipulate it. You can just do something like `Check.Quick (fun (s: NonNull<string>) -> s.Get.Length > 0)`. See https://fsharp.github.io/FsCheck/Properties.html for more details.

**Comment by kkm000** [comment]
I see. So essentially `Prop.forAll (Arb.from<NonNull<string>>)` is implicit here. Thanks.

**Comment by kkm000** [comment]
On a meta note, what would be the best forum to ask basic questions about FsCheck? GitHub issues are, well issues, not a QA forum. I know there is a tag at SO, but SO is quite snubby, so asking a question unless you know 2/3 of an answer will get the question deleted (I am trying to answer questions marked for deletion as fast as I can before they are gone--I do sympathize with clueless people, but myself do not want to be in that boat), and I am indeed asking dumb newbie questions.

**Comment by mausch** [comment]
I don't answer on Stackoverflow any more (except for the occasional comment) due to the problems you describe and many others. However Kurt and others do, so if you're willing to put up with the issues of Stackoverflow you might get an answer quicker.
I don't mind using Github issues as a QA forum. Then again, Kurt is the maintainer so that's really up to him if we should use it like this.
You can also post your questions to https://groups.google.com/forum/#!searchin/fsharp-opensource .

**Comment by kurtschelfthout** [comment]
I have a slight preference for SO atm; Tag with fscheck and I'll get an email and try to reply. I doubt you'll get beginners questions closed on FsCheck; if you do please let me know I'll try to reason with them. 

But I don't mind you asking questions here either at all. Whatever feels comfortable. 

I don't follow the open source list actively, feel free to cc me though if you think I can help. 

I mostly dislike Twitter (bad forum) and email (not public).
