### ISSUE TITLE
`True` conflict when both FsUnit and FsCheck are open

### ISSUE THREAD

**Issue by kkm000** [fsharp/FsCheck#82]
Not sure if this is something that can or should be fixed, but these 2 frameworks are likely to be used together in testing F# code, so it may make sense to think out a fix.

In this code piece
```F#
open FsUnit (* 1 *)
open FsCheck (* 2 *)
open NUnit.Framework

[<Test>]
let ``Minimal abstract grammar`` () =
   false |> should be True
```

`True` is construed as a `True` constructor of the `FsCheck.Outcome` union type. A workaround is to swap the two open directives (*1*) and (*2*), but I am not sure how far this would get me. But writing something like 

```F#
   r.Export |> should be (FsUnit.TopLevelOperators.True)
```

indeed goes against the grain of FsUnit.

**Comment by kurtschelfthout** [comment]
Yes, FsCheck should not be exporting True I think. I'll take a closer look.

**Comment by kurtschelfthout** [comment]
It's used indirectly for custom test runners to figure out what the outcome of a test is (True, False, Timeout, Rejected etc) so I can't easily make it internal. Reversing the order of opens it is, I guess...

**Comment by kkm000** [comment]
Is it not possible to rename it either?

**Comment by kurtschelfthout** [comment]
Would be a breaking change.

**Comment by mausch** [comment]
I'd recommend marking Outcome with `[<RequireQualifiedAccess>]`. The cases of this type are pretty common names which makes conflicts like this more likely.
It would be a breaking change but it's a type typically only used for integration with other test frameworks, there are only a handful of them.

**Comment by kurtschelfthout** [comment]
Warm. It's everyone who implements IRunner though, not only extensions. 

Ok, guess we'll have a 2.0 release with a few breaking or potentially breaking small changes. There's a few others.

**Comment by kkm000** [comment]
> Would be a breaking change.
@kurtschelfthout: so were [this](https://github.com/fsharp/FsCheck/commit/85530e) and [this](https://github.com/fsharp/FsCheck/commit/17af4a). The first, the nulls, was a *huge* behavior change, not even slightly mentioned in the documentation, unless I overlooked it. My tests went up in smoke. Ah, come on, who cares about breaking changes... :(

**Comment by kurtschelfthout** [comment]
Anything goes before 1.0. See semver.org.

I will probably make this change if I can batch it up with a few other breaking changes. By itself, it's not worth releasing a 2.0 for.

**Comment by kkm000** [comment]
@kurtschelfthout: I see. Sorry I did not pay attention to the version number. The beauty of standards is that there are so many to choose from! :)
