### ISSUE TITLE
Create strong named packages

### ISSUE THREAD

**Issue by forki** [fsharp/FsCheck#90]
In https://github.com/Microsoft/visualfsharp/pull/361 we need a strong named package. I wonder if FsCheck could strong name all its packages with an open key just to work around this.
It should be doable during the build / release process.

**Comment by kurtschelfthout** [comment]
See #73 - am less than enthusiastic about this to say the least. Maybe if we create create a separate NuGet package with the AssemblyVersion constant or something. Still seems like a lot of work for very small benefit.

**Comment by forki** [comment]
Fair enough. We should find a way in visualfsharp
