### ISSUE TITLE
Q: generate non-empty string-keyed maps?

### ISSUE THREAD

**Issue by haf** [fsharp/FsCheck#96]
This doesn't seem to work:

``` fsharp
open Fuchu
open FsCheck

type Arbs =
  static member SafeString () =
    Arb.Default.String () |> Arb.filter (fun str -> str <> null && not (str = ""))

  static member NonEmptyStringMaps () =
    Arb.Default.Map () |> Arb.filter (fun m -> m |> Map.toList |> List.forall (fun (k,v) -> k <> "" && k <> null))

let fsCheckConfig = { Config.Default with Arbitrary = [ typeof<Arbs> ] }

// ----
testPropertyWithConfig fsCheckConfig "can roundtrip" <| fun (evt : Evt) ->
 Assert.Equal("roundtrip", evt, roundTrip evt)
```

**Comment by kurtschelfthout** [comment]
What does not work about it?

``Check.One(fsCheckConfig,(fun (s:string,m:Map<string,int>) -> not <| String.IsNullOrEmpty s && m |> Map.forall (fun s v -> not <| String.IsNullOrEmpty s)))``

passes the test for me.

**Comment by mausch** [comment]
Not sure what `Evt` is but I just tried the Map check with Fuchu and it passes:

```fsharp
open System
open Fuchu
open FsCheck

type Arbs =
  static member SafeString () =
    Arb.Default.String () |> Arb.filter (fun str -> str <> null && not (str = ""))

  static member NonEmptyStringMaps () =
    Arb.Default.Map () |> Arb.filter (fun m -> m |> Map.toList |> List.forall (fun (k,v) -> k <> "" && k <> null))

let fsCheckConfig = { Config.Default with Arbitrary = [ typeof<Arbs> ] }

let test = 
    testPropertyWithConfig fsCheckConfig "can roundtrip" <| 
        fun (s:string,m:Map<string,int>) -> not <| String.IsNullOrEmpty s && m |> Map.forall (fun s v -> not <| String.IsNullOrEmpty s)

[<EntryPoint>]
let main argv = run test
```

**Comment by haf** [comment]
It didn't *seem* to work. The error was in the surrounding code - the JSON parser to be exact -- which didn't support whitespace-only keys (and FsCheck generated `" "`). Thank you for your help; this time the problem was behind this keyboard.

**Comment by haf** [comment]
Upon further investigation; no, I still have the problem. Might it be so that since I have an alias for Map<string, string> this means my Arbitrary doesn't match it?

**Comment by haf** [comment]
No, it's because FsCheck generates '' whichever char that is! ;)

**Comment by mausch** [comment]
Weird, AFAIK aliases are erased. Could you post a failing example?
